### PR TITLE
Flat records for limits/colimits

### PR DESCRIPTION
**Pull request by TOTBWF**
# Description

This PR flattens out `Binary-products` et. al into flat records to get better printing.

Currently, this is a draft to get API feedback!

## Checklist

Before submitting a merge request, please check the items below:

- [x] I've read [the contributing guidelines](https://github.com/plt-amy/1lab/blob/main/CONTRIBUTING.md).
- [x] The imports of new modules have been sorted with `support/sort-imports.hs` (or `nix run --experimental-features nix-command -f . sort-imports`).
- [x] All new code blocks have "agda" as their language.

If your change affects many files without adding substantial content, and
you don't want your name to appear on those pages (for example, treewide
refactorings or reformattings), start the commit message and PR title with `chore:`.

### CODE REVIEW

**Comment by Lavenza** [comment]
[Pull request preview](https://preview.1lab.dev/417)

**Comment by ncfavier** [comment]
Could we have a test/reproducer for the printing issues with, say, binary products?

**Comment by TOTBWF** [comment]
I think @plt-amy had a good real world example in https://gist.github.com/plt-amy/9f1efaaef2fe15baf4965be21e60994b, we could use the code that generated the nightmare for that

**Comment by ncfavier** [comment]
I guess things like `δ-natural` can serve as test cases. Without this PR the goal is

```
is-product.⟨ Product.has-is-product (all-products y y) , id ⟩
      id
      ∘ f
      ≡
      is-product.⟨ Product.has-is-product (all-products y y) ,
      f ∘ Product.π₁ (all-products x x) ⟩
      (f ∘ Product.π₂ (all-products x x))
      ∘ is-product.⟨ Product.has-is-product (all-products x x) , id ⟩ id
```

With this PR it becomes `⟨ id , id ⟩ ∘ f ≡ ⟨ f ∘ π₁ , f ∘ π₂ ⟩ ∘ ⟨ id , id ⟩`. Much better!

**Pull request closed without merging**
